#mysql
c3p0.jdbcUrl=${c3p0_jdbcUrl}
c3p0.driverClass=${c3p0_driverClass}
c3p0.user=${c3p0_user}
c3p0.password=${c3p0_password}
c3p0.initialPoolSize=${c3p0_initialPoolSize}
c3p0.minPoolSize=${c3p0_minPoolSize}
c3p0.maxPoolSize=${c3p0_maxPoolSize}
c3p0.maxIdleTime=${c3p0_maxIdleTime}
c3p0.acquireRetryAttempts=${c3p0_acquireRetryAttempts}
c3p0.acquireRetryDelay=${c3p0_acquireRetryDelay}
c3p0.checkoutTimeout=${c3p0_checkoutTimeout}
c3p0.maxStatements=${c3p0_maxStatements}
c3p0.numHelperThreads=${c3p0_numHelperThreads}
c3p0.testConnectionOnCheckin=${c3p0_testConnectionOnCheckin}
c3p0.preferredTestQuery=${c3p0_preferredTestQuery}